name: upload-sourcemap-to-datadog
on:
  push:
    branches:
      - main
    paths:
      - apps/docs/**
      - apps/web/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.27.0

      - name: install datadog-ci
        run: pnpm install --global @datadog/datadog-ci

      - name: Install pnpm
        run: pnpm i --frozen-lockfile

      - name: Run pnpm build
        run: pnpm build

      - name: upload sourcemap for web
        run: |
          datadog-ci sourcemaps upload ./apps/web/.next/static \
          --service=shiiinji-blog \
          --release-version=test9.12 \
          --minified-path-prefix=/_next/static \
        env:
          DATADOG_SITE: us5.datadoghq.com
          DATADOG_API_HOST: api.us5.datadoghq.com
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          GITHUB_SHA: ${{ github.sha }}

      - name: upload sourcemap for doc
        run: |
          datadog-ci sourcemaps upload ./apps/docs/.next/static \
          --service=shiiinji-doc \
          --release-version=$GITHUB_SHA \
          --minified-path-prefix=/_next/static \
        env:
          DATADOG_SITE: us5.datadoghq.com
          DATADOG_API_HOST: api.us5.datadoghq.com
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          GITHUB_SHA: ${{ github.sha }}

